### ISSUE TITLE
Expose functionality from `update` script into library functions

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/evmchains#15]
I would like to be able to retrieve data from any chain adhocly , like if it was not yet added to this library.
I think we can do this via some of the stuff in update.py - a small chainlis client library or something..

**Comment by mikeshultz** [comment]
I don't especially want to add any dependencies and especially no HTTP requests to this lib.  Try to KISS it.  

If updating this for network support is annoying (assuming that's why you posted this), what if instead we just included all networks from the source?  Looking at the source data this would be no more than like 6MB, which doesn't seem unreasonable for an installed package.

**Comment by mikeshultz** [comment]
Actually, I'm not entirely sure we can do either.  We still need to match the Ape ecosystem:network tuple to a chain ID.

**Comment by antazoey** [comment]
Potentially can make an `evmchains-connect` library or update Ape to include more of these behaviors.

**Comment by mikeshultz** [comment]
The big point of this package was mapping the ecosystem:network tuple to a chain ID.  Everything else is gravy. I assume if you already had a chain ID from your adhoc net you'd have an RPC connection so using this package is a bit of a chicken and an egg.
