### ISSUE TITLE
feature request: allow specifying desired client version in `get_random_rpc()`

### ISSUE THREAD

**Issue by antazoey** [ApeWorX/evmchains#17]
Sometimes I have to repeatedly call `get_random_rpc()` until I get a node of a certain type.  For example, I am testing something with Parity, I have to keep retrying until i get a node with parity client version. It would be nice if I can give it a parameter for this so it only returns to me a random RPC of a certain client version (e.g. geth or reth)

**Comment by mikeshultz** [comment]
Don't think that information exists in this data set. And still think deps like an HTTP client should stay out of this lib. 

Instead of leveraging a random return though, what if you just iterated through [`get_rpcs(ecosystem, network)`](https://github.com/ApeWorX/evmchains/blob/a6f6c5a18d4e1a996bafe299a2bc0136c95c5c17/evmchains/__init__.py#L23C5-L23C43) rather than trying to use `get_random_rpc()`?
